name: Continuous Delivery

on:
  push:
    branches:
      - develop

jobs:
  export-game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
    - name: download templates
      run: |
        wget --no-verbose https://downloads.tuxfamily.org/godotengine/3.3.2/mono/Godot_v3.3.2-stable_mono_export_templates.tpz
        mkdir -p ~/templates-3.3.2.stable.mono
        unzip -q Godot_v3.3.2-stable_mono_export_templates.tpz -d ~/templates-3.3.2.stable.mono
        mkdir -p /home/runner/.local/share/godot/templates/3.3.2.stable.mono
        mv ~/templates-3.3.2.stable.mono/templates/* /home/runner/.local/share/godot/templates/3.3.2.stable.mono
    - name: download godot
      run: |
        wget --no-verbose https://downloads.tuxfamily.org/godotengine/3.3.2/mono/Godot_v3.3.2-stable_mono_linux_headless_64.zip
        unzip -q Godot_v3.3.2-stable_mono_linux_headless_64.zip
    - name: export game
      run: |
        mkdir -p out
        cd Godot_v3.3.2-stable_mono_linux_headless_64
        ./Godot_v3.3.2-stable_mono_linux_headless.64 --path '../' --export "Windows Desktop"
    - name: upload logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: /home/runner/.local/share/godot/mono/mono_logs
    - name: upload export
      uses: actions/upload-artifact@v2
      with:
        name: export
        path: ${GITHUB_WORKSPACE}/out
