name: Continuous Delivery

on:
  push:
    branches:
      - develop

jobs:
  export-game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
    - name: download godot & template
      run: |
        wget --no-verbose https://downloads.tuxfamily.org/godotengine/3.3.2/mono/Godot_v3.3.2-stable_mono_linux_headless_64.zip
        wget --no-verbose https://downloads.tuxfamily.org/godotengine/3.3.2/mono/Godot_v3.3.2-stable_mono_export_templates.tpz
        unzip -q Godot_v3.3.2-stable_mono_linux_headless_64.zip
        mkdir -p ~/.godot
        unzip -q Godot_v3.3.2-stable_mono_export_templates.tpz -d ~/.godot
        cd Godot_v3.3.2-stable_mono_linux_headless_64
        ./Godot_v3.3.2-stable_mono_linux_headless.64 --path '../' --export "Windows Desktop"
    # - name: upload artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: godot-roguelike-develop
    #     path: /home/runner/.local/share/godot/builds/Windows Desktop
